default["test_looper_server"]["service_account"] = "ubuntu"
default["test_looper_server"]["install_dir"] = "/opt/test-looper-server"
default["test_looper_server"]["git_repo"] = "git@github.com:ufora/main.git"
default["test_looper_server"]["git_branch"] = "test-looper"
default["test_looper_server"]["github_deploy_key"] = ".ssh/id_deploy"
default["test_looper_server"]["github_login"] = "ufora-bot"
